// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "SmartSync.h"
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include <sstream>
#include "checksum.hpp"
#include "mytypes.h"
#include "common.h"
#include "package.hpp"
#include "search.hpp"
#include "file.hpp"
#include <mutex>
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>
#include <thrift/concurrency/ThreadManager.h>
#include <thrift/concurrency/PosixThreadFactory.h>
#include <thrift/server/TThreadedServer.h>

//cannot use namespace std, since it will lead to shared_ptr ambiguous
using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;
using namespace ::apache::thrift::concurrency;

using boost::shared_ptr;

static FileWorker *fworker = NULL;
static ChksumWorker *chkworker = NULL;
static Package *pkgworker = NULL;
static SearchWorker *searchworker = NULL;

class SmartSyncHandler : virtual public SmartSyncIf {
 public:
  SmartSyncHandler() {
    // Your initialization goes here
  }

  void writeFile2Server(StatusReport& _return, const RFile& rFile) {
    // Your implementation goes here
    dprintf("writeFile\n");
    if (fworker->writefile(rFile) != -1) {
        _return.__set_status(Status::SUCCESS);
    } else {
        _return.__set_status(Status::FAIL);
    }
  }

  void getFileFromServer(std::string& _return, const std::string& fName) {
    // Your implementation goes here
    dprintf("getFileFromServer\n");
  }

  void updateLocal(std::vector<Filedes> & _return, const std::vector<Filechk> & chks) {
    // Your implementation goes here
    dprintf("updateLocal\n");
    
    if ((int)chks.size() * 1000000 < fworker->getFileSize()) {
        _return = fworker->getFiledes();     
    } else {
        pkgworker->initchksums(chks);
        searchworker->init(pkgworker->getchksums());

        searchworker->find();
        _return = pkgworker->getFiledes(); 
    }
  }

  void updateServer(StatusReport& _return, const std::vector<Filedes> & des) {
    // Your implementation goes here
    dprintf("updateServer\n");
    if (fworker->updateFile(des)) {
        _return.__set_status(Status::SUCCESS);
    } else {
        _return.__set_status(Status::FAIL);
    }
  }

  void request(std::vector<Filechk> & _return) {
    // Your implementation goes here
    dprintf("request filechecks list\n");
    vector<string> file;
    ifstream ifs(fworker->getPath().c_str());
    double filesize = fworker->getFileSize();
    int blocksize = fworker->getBlockSize();
    if (ifs) {
        for (int i = 0; i < (int)ceil(filesize/blocksize); ++i) {
            char *buf = new char[blocksize+1];
            ifs.read(buf,blocksize);
            buf[ifs.gcount()] = '\0';
            file.push_back(buf);
            delete [] buf;
        }
    } else {
        cerr<<"open file error"<<endl;
        exit(-1);
    }
    ifs.close();
    int l;
    int bsize = fworker->getBlockSize();
    int fsize = fworker->getFileSize();
    for (int i = 0; i < (int)file.size(); ++i) {
        if (i == (int)file.size() - 1) {
            l = fsize - i*bsize-1;
        } else {
            l = bsize-1;
        }
        //cout<<"len is "<<l+1<<" file block content is "<<file[i]<<endl;
        checksum num1 = 1;
        checksum num2 = 0;
        //cout<<"k is "<<i*bsize<<" l is "<<i*bsize+l<<endl;
        checksum rchk = chkworker->rolling_chksum1(file[i],i*bsize,i*bsize + l,num1,num2);
        string md5chk = chkworker->md5_chksum(file[i]);
        Filechk temp;
        temp.__set_rollchk(rchk);
        temp.__set_md5chk(md5chk);
        temp.__set_block(i);
        temp.__set_num1(num1);
        temp.__set_num2(num2);

        _return.push_back(temp);
    }
    /*
    cout<<"in request show _return "<<endl;
    for (int i = 0; i < (int)_return.size();++i) {
        cout<<i<< " roll:"<<_return[i].rollchk
            <<" num1:"<<_return[i].num1
            <<" num2:"<<_return[i].num2
            <<" md5:"<<_return[i].md5chk
            <<" block:"<<_return[i].block
            <<endl;
    }
    cout<<"in request end show"<<endl;
    */
  }

  void checkFile(StatusReport& _return, const RFileMetadata& meta) {
    // Your implementation goes here
    std::string filename = meta.filename;
    dprintf("checkFile %s's status is %d\n",meta.filename.c_str(),filestatus[meta.filename]);
    //check file status, if it exists and is modifying by other client, if will do nothing
    mtx.lock();
    if (filestatus.find(meta.filename) == filestatus.end())
        filestatus[filename] = 1;
    mtx.unlock();
    if (filestatus.find(meta.filename) != filestatus.end() && filestatus[meta.filename] != 0 && meta.target == 0) {
        dprintf("%s is modifying by server\n",meta.filename.c_str());
        _return.__set_status(Status::BLOCK);
        return;
    }
    //clean pkgworker
    pkgworker->clean();
    fworker->setPath("./files/"+meta.filename);
        
    //struct stat st;
    NameDataMap mymap = fworker->getMap();

    Timestamp t = mymap[meta.filename].updated;
    //dprintf("Time of file on server is %s\nTime of send from client is %s\n",t.c_str(),meta.updated.c_str());

    //string filename = meta.filename;
    if (access(fworker->getPath().c_str(),F_OK) == 0) {
        //means exist
        //check content whether is the same
        //string fcontent;
        //first check md5, if not same, then check update time
        //dprintf("file path is %s\n",fworker->getPath().c_str());
        ifstream ifs(fworker->getPath().c_str());
        if (ifs) {
            ifs.seekg(0,ifs.end);
            int len = ifs.tellg();

            fworker->setFileSize(len);

            ifs.seekg(0,ifs.beg);
            char* buf = new char[len+1];
            ifs.read(buf,len);
            buf[ifs.gcount()] = '\0';
            string fmd5 = md5(buf);
            delete []buf;
            ifs.close();
            //cout<<(fmd5 == meta.contenthash)<<endl;
            if (fmd5 == meta.contenthash) {
                //it means the same
                dprintf("same\n");
                _return.__set_status(Status::SAME);
            } else {
                dprintf("not same and before lock\n");
                mtx.lock();
                filestatus[meta.filename] = 1;
                mtx.unlock(); 
                dprintf("after unlock\n");
                if (t < meta.updated) {
                    //client newer
                    dprintf("client is newer\n");
                    _return.__set_status(Status::NEWER);
                } else if (t > meta.updated) {
                    //server newer
                    dprintf("client is older\n");
                    _return.__set_status(Status::OLDER);
                } else {
                    ;
                }
            }
        }
    } else {
        //not exist
        _return.__set_status(Status::NOEXIST);
    }
    dprintf("end check\n");
  }

};

int main(int argc, char **argv) {
  if (argc < 1) {
    cout<<"You should exec like ./server 1024\n 1024 stands for blocksize is 1024Byte.\n";
    return 0;
  }
  int port = 9090;
  boost::shared_ptr<SmartSyncHandler> handler(new SmartSyncHandler());
  boost::shared_ptr<TProcessor> processor(new SmartSyncProcessor(handler));
  boost::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  boost::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  boost::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  boost::shared_ptr<ThreadManager> threadManager(ThreadManager::newSimpleThreadManager(4));
  boost::shared_ptr<PosixThreadFactory> threadFactory(new PosixThreadFactory());
  threadManager->threadFactory(threadFactory);
  threadManager->start();

  TThreadedServer server(processor, serverTransport, transportFactory, protocolFactory);
  
  fworker = new FileWorker();
  chkworker = new ChksumWorker();
  pkgworker = new Package();
  searchworker = new SearchWorker(chkworker,fworker,pkgworker);  

  fworker->initFolder();
  fworker->setBlockSize(atoi(argv[1]));

  server.serve();
  return 0;
}

