/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SmartSync_H
#define SmartSync_H

#include <thrift/TDispatchProcessor.h>
#include "smartSync_types.h"



class SmartSyncIf {
 public:
  virtual ~SmartSyncIf() {}
  virtual void update(RFile& _return, const RFile& rfile, const NodeID& node) = 0;
  virtual void request(RFile& _return, const NodeID& node) = 0;
  virtual void checkFile(RFileMetadata& _return, const RFileMetadata& meta, const NodeID& node) = 0;
};

class SmartSyncIfFactory {
 public:
  typedef SmartSyncIf Handler;

  virtual ~SmartSyncIfFactory() {}

  virtual SmartSyncIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(SmartSyncIf* /* handler */) = 0;
};

class SmartSyncIfSingletonFactory : virtual public SmartSyncIfFactory {
 public:
  SmartSyncIfSingletonFactory(const boost::shared_ptr<SmartSyncIf>& iface) : iface_(iface) {}
  virtual ~SmartSyncIfSingletonFactory() {}

  virtual SmartSyncIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(SmartSyncIf* /* handler */) {}

 protected:
  boost::shared_ptr<SmartSyncIf> iface_;
};

class SmartSyncNull : virtual public SmartSyncIf {
 public:
  virtual ~SmartSyncNull() {}
  void update(RFile& /* _return */, const RFile& /* rfile */, const NodeID& /* node */) {
    return;
  }
  void request(RFile& /* _return */, const NodeID& /* node */) {
    return;
  }
  void checkFile(RFileMetadata& /* _return */, const RFileMetadata& /* meta */, const NodeID& /* node */) {
    return;
  }
};

typedef struct _SmartSync_update_args__isset {
  _SmartSync_update_args__isset() : rfile(false), node(false) {}
  bool rfile :1;
  bool node :1;
} _SmartSync_update_args__isset;

class SmartSync_update_args {
 public:

  static const char* ascii_fingerprint; // = "A33A10555116172CEAF3CAE03B08B77A";
  static const uint8_t binary_fingerprint[16]; // = {0xA3,0x3A,0x10,0x55,0x51,0x16,0x17,0x2C,0xEA,0xF3,0xCA,0xE0,0x3B,0x08,0xB7,0x7A};

  SmartSync_update_args(const SmartSync_update_args&);
  SmartSync_update_args& operator=(const SmartSync_update_args&);
  SmartSync_update_args() {
  }

  virtual ~SmartSync_update_args() throw();
  RFile rfile;
  NodeID node;

  _SmartSync_update_args__isset __isset;

  void __set_rfile(const RFile& val);

  void __set_node(const NodeID& val);

  bool operator == (const SmartSync_update_args & rhs) const
  {
    if (!(rfile == rhs.rfile))
      return false;
    if (!(node == rhs.node))
      return false;
    return true;
  }
  bool operator != (const SmartSync_update_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SmartSync_update_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const SmartSync_update_args& obj);
};


class SmartSync_update_pargs {
 public:

  static const char* ascii_fingerprint; // = "A33A10555116172CEAF3CAE03B08B77A";
  static const uint8_t binary_fingerprint[16]; // = {0xA3,0x3A,0x10,0x55,0x51,0x16,0x17,0x2C,0xEA,0xF3,0xCA,0xE0,0x3B,0x08,0xB7,0x7A};


  virtual ~SmartSync_update_pargs() throw();
  const RFile* rfile;
  const NodeID* node;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const SmartSync_update_pargs& obj);
};

typedef struct _SmartSync_update_result__isset {
  _SmartSync_update_result__isset() : success(false), systemException(false) {}
  bool success :1;
  bool systemException :1;
} _SmartSync_update_result__isset;

class SmartSync_update_result {
 public:

  static const char* ascii_fingerprint; // = "4E9ECDC6DA2700E057A89E1DD5437A44";
  static const uint8_t binary_fingerprint[16]; // = {0x4E,0x9E,0xCD,0xC6,0xDA,0x27,0x00,0xE0,0x57,0xA8,0x9E,0x1D,0xD5,0x43,0x7A,0x44};

  SmartSync_update_result(const SmartSync_update_result&);
  SmartSync_update_result& operator=(const SmartSync_update_result&);
  SmartSync_update_result() {
  }

  virtual ~SmartSync_update_result() throw();
  RFile success;
  SystemException systemException;

  _SmartSync_update_result__isset __isset;

  void __set_success(const RFile& val);

  void __set_systemException(const SystemException& val);

  bool operator == (const SmartSync_update_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(systemException == rhs.systemException))
      return false;
    return true;
  }
  bool operator != (const SmartSync_update_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SmartSync_update_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const SmartSync_update_result& obj);
};

typedef struct _SmartSync_update_presult__isset {
  _SmartSync_update_presult__isset() : success(false), systemException(false) {}
  bool success :1;
  bool systemException :1;
} _SmartSync_update_presult__isset;

class SmartSync_update_presult {
 public:

  static const char* ascii_fingerprint; // = "4E9ECDC6DA2700E057A89E1DD5437A44";
  static const uint8_t binary_fingerprint[16]; // = {0x4E,0x9E,0xCD,0xC6,0xDA,0x27,0x00,0xE0,0x57,0xA8,0x9E,0x1D,0xD5,0x43,0x7A,0x44};


  virtual ~SmartSync_update_presult() throw();
  RFile* success;
  SystemException systemException;

  _SmartSync_update_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const SmartSync_update_presult& obj);
};

typedef struct _SmartSync_request_args__isset {
  _SmartSync_request_args__isset() : node(false) {}
  bool node :1;
} _SmartSync_request_args__isset;

class SmartSync_request_args {
 public:

  static const char* ascii_fingerprint; // = "2BD9E1CC52BCB0899198EEADB3593B00";
  static const uint8_t binary_fingerprint[16]; // = {0x2B,0xD9,0xE1,0xCC,0x52,0xBC,0xB0,0x89,0x91,0x98,0xEE,0xAD,0xB3,0x59,0x3B,0x00};

  SmartSync_request_args(const SmartSync_request_args&);
  SmartSync_request_args& operator=(const SmartSync_request_args&);
  SmartSync_request_args() {
  }

  virtual ~SmartSync_request_args() throw();
  NodeID node;

  _SmartSync_request_args__isset __isset;

  void __set_node(const NodeID& val);

  bool operator == (const SmartSync_request_args & rhs) const
  {
    if (!(node == rhs.node))
      return false;
    return true;
  }
  bool operator != (const SmartSync_request_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SmartSync_request_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const SmartSync_request_args& obj);
};


class SmartSync_request_pargs {
 public:

  static const char* ascii_fingerprint; // = "2BD9E1CC52BCB0899198EEADB3593B00";
  static const uint8_t binary_fingerprint[16]; // = {0x2B,0xD9,0xE1,0xCC,0x52,0xBC,0xB0,0x89,0x91,0x98,0xEE,0xAD,0xB3,0x59,0x3B,0x00};


  virtual ~SmartSync_request_pargs() throw();
  const NodeID* node;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const SmartSync_request_pargs& obj);
};

typedef struct _SmartSync_request_result__isset {
  _SmartSync_request_result__isset() : success(false), systemException(false) {}
  bool success :1;
  bool systemException :1;
} _SmartSync_request_result__isset;

class SmartSync_request_result {
 public:

  static const char* ascii_fingerprint; // = "4E9ECDC6DA2700E057A89E1DD5437A44";
  static const uint8_t binary_fingerprint[16]; // = {0x4E,0x9E,0xCD,0xC6,0xDA,0x27,0x00,0xE0,0x57,0xA8,0x9E,0x1D,0xD5,0x43,0x7A,0x44};

  SmartSync_request_result(const SmartSync_request_result&);
  SmartSync_request_result& operator=(const SmartSync_request_result&);
  SmartSync_request_result() {
  }

  virtual ~SmartSync_request_result() throw();
  RFile success;
  SystemException systemException;

  _SmartSync_request_result__isset __isset;

  void __set_success(const RFile& val);

  void __set_systemException(const SystemException& val);

  bool operator == (const SmartSync_request_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(systemException == rhs.systemException))
      return false;
    return true;
  }
  bool operator != (const SmartSync_request_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SmartSync_request_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const SmartSync_request_result& obj);
};

typedef struct _SmartSync_request_presult__isset {
  _SmartSync_request_presult__isset() : success(false), systemException(false) {}
  bool success :1;
  bool systemException :1;
} _SmartSync_request_presult__isset;

class SmartSync_request_presult {
 public:

  static const char* ascii_fingerprint; // = "4E9ECDC6DA2700E057A89E1DD5437A44";
  static const uint8_t binary_fingerprint[16]; // = {0x4E,0x9E,0xCD,0xC6,0xDA,0x27,0x00,0xE0,0x57,0xA8,0x9E,0x1D,0xD5,0x43,0x7A,0x44};


  virtual ~SmartSync_request_presult() throw();
  RFile* success;
  SystemException systemException;

  _SmartSync_request_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const SmartSync_request_presult& obj);
};

typedef struct _SmartSync_checkFile_args__isset {
  _SmartSync_checkFile_args__isset() : meta(false), node(false) {}
  bool meta :1;
  bool node :1;
} _SmartSync_checkFile_args__isset;

class SmartSync_checkFile_args {
 public:

  static const char* ascii_fingerprint; // = "C65734E20AD62980068E4AF990098466";
  static const uint8_t binary_fingerprint[16]; // = {0xC6,0x57,0x34,0xE2,0x0A,0xD6,0x29,0x80,0x06,0x8E,0x4A,0xF9,0x90,0x09,0x84,0x66};

  SmartSync_checkFile_args(const SmartSync_checkFile_args&);
  SmartSync_checkFile_args& operator=(const SmartSync_checkFile_args&);
  SmartSync_checkFile_args() {
  }

  virtual ~SmartSync_checkFile_args() throw();
  RFileMetadata meta;
  NodeID node;

  _SmartSync_checkFile_args__isset __isset;

  void __set_meta(const RFileMetadata& val);

  void __set_node(const NodeID& val);

  bool operator == (const SmartSync_checkFile_args & rhs) const
  {
    if (!(meta == rhs.meta))
      return false;
    if (!(node == rhs.node))
      return false;
    return true;
  }
  bool operator != (const SmartSync_checkFile_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SmartSync_checkFile_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const SmartSync_checkFile_args& obj);
};


class SmartSync_checkFile_pargs {
 public:

  static const char* ascii_fingerprint; // = "C65734E20AD62980068E4AF990098466";
  static const uint8_t binary_fingerprint[16]; // = {0xC6,0x57,0x34,0xE2,0x0A,0xD6,0x29,0x80,0x06,0x8E,0x4A,0xF9,0x90,0x09,0x84,0x66};


  virtual ~SmartSync_checkFile_pargs() throw();
  const RFileMetadata* meta;
  const NodeID* node;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const SmartSync_checkFile_pargs& obj);
};

typedef struct _SmartSync_checkFile_result__isset {
  _SmartSync_checkFile_result__isset() : success(false), systemException(false) {}
  bool success :1;
  bool systemException :1;
} _SmartSync_checkFile_result__isset;

class SmartSync_checkFile_result {
 public:

  static const char* ascii_fingerprint; // = "A0DC2A879CBCFCA16A672C40DD88C2B4";
  static const uint8_t binary_fingerprint[16]; // = {0xA0,0xDC,0x2A,0x87,0x9C,0xBC,0xFC,0xA1,0x6A,0x67,0x2C,0x40,0xDD,0x88,0xC2,0xB4};

  SmartSync_checkFile_result(const SmartSync_checkFile_result&);
  SmartSync_checkFile_result& operator=(const SmartSync_checkFile_result&);
  SmartSync_checkFile_result() {
  }

  virtual ~SmartSync_checkFile_result() throw();
  RFileMetadata success;
  SystemException systemException;

  _SmartSync_checkFile_result__isset __isset;

  void __set_success(const RFileMetadata& val);

  void __set_systemException(const SystemException& val);

  bool operator == (const SmartSync_checkFile_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(systemException == rhs.systemException))
      return false;
    return true;
  }
  bool operator != (const SmartSync_checkFile_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SmartSync_checkFile_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const SmartSync_checkFile_result& obj);
};

typedef struct _SmartSync_checkFile_presult__isset {
  _SmartSync_checkFile_presult__isset() : success(false), systemException(false) {}
  bool success :1;
  bool systemException :1;
} _SmartSync_checkFile_presult__isset;

class SmartSync_checkFile_presult {
 public:

  static const char* ascii_fingerprint; // = "A0DC2A879CBCFCA16A672C40DD88C2B4";
  static const uint8_t binary_fingerprint[16]; // = {0xA0,0xDC,0x2A,0x87,0x9C,0xBC,0xFC,0xA1,0x6A,0x67,0x2C,0x40,0xDD,0x88,0xC2,0xB4};


  virtual ~SmartSync_checkFile_presult() throw();
  RFileMetadata* success;
  SystemException systemException;

  _SmartSync_checkFile_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const SmartSync_checkFile_presult& obj);
};

class SmartSyncClient : virtual public SmartSyncIf {
 public:
  SmartSyncClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  SmartSyncClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void update(RFile& _return, const RFile& rfile, const NodeID& node);
  void send_update(const RFile& rfile, const NodeID& node);
  void recv_update(RFile& _return);
  void request(RFile& _return, const NodeID& node);
  void send_request(const NodeID& node);
  void recv_request(RFile& _return);
  void checkFile(RFileMetadata& _return, const RFileMetadata& meta, const NodeID& node);
  void send_checkFile(const RFileMetadata& meta, const NodeID& node);
  void recv_checkFile(RFileMetadata& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class SmartSyncProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<SmartSyncIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (SmartSyncProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_update(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_request(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_checkFile(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  SmartSyncProcessor(boost::shared_ptr<SmartSyncIf> iface) :
    iface_(iface) {
    processMap_["update"] = &SmartSyncProcessor::process_update;
    processMap_["request"] = &SmartSyncProcessor::process_request;
    processMap_["checkFile"] = &SmartSyncProcessor::process_checkFile;
  }

  virtual ~SmartSyncProcessor() {}
};

class SmartSyncProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  SmartSyncProcessorFactory(const ::boost::shared_ptr< SmartSyncIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< SmartSyncIfFactory > handlerFactory_;
};

class SmartSyncMultiface : virtual public SmartSyncIf {
 public:
  SmartSyncMultiface(std::vector<boost::shared_ptr<SmartSyncIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~SmartSyncMultiface() {}
 protected:
  std::vector<boost::shared_ptr<SmartSyncIf> > ifaces_;
  SmartSyncMultiface() {}
  void add(boost::shared_ptr<SmartSyncIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void update(RFile& _return, const RFile& rfile, const NodeID& node) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->update(_return, rfile, node);
    }
    ifaces_[i]->update(_return, rfile, node);
    return;
  }

  void request(RFile& _return, const NodeID& node) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->request(_return, node);
    }
    ifaces_[i]->request(_return, node);
    return;
  }

  void checkFile(RFileMetadata& _return, const RFileMetadata& meta, const NodeID& node) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->checkFile(_return, meta, node);
    }
    ifaces_[i]->checkFile(_return, meta, node);
    return;
  }

};



#endif
