/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef smartSync_CONSTANTS_H
#define smartSync_CONSTANTS_H

#include "smartSync_types.h"



class smartSyncConstants {
 public:
  smartSyncConstants();

};

extern const smartSyncConstants g_smartSync_constants;



#endif
