/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef smartSync_TYPES_H
#define smartSync_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>




struct Status {
  enum type {
    SAME = 0,
    NOEXIST = 1,
    OLDER = 2,
    NEWER = 3,
    FAIL = 4,
    SUCCESS = 5
  };
};

extern const std::map<int, const char*> _Status_VALUES_TO_NAMES;

typedef int64_t Timestamp;

class SystemException;

class StatusReport;

class RFileMetadata;

class Filedes;

class Filechk;

class RFile;

typedef struct _SystemException__isset {
  _SystemException__isset() : message(false) {}
  bool message :1;
} _SystemException__isset;

class SystemException : public ::apache::thrift::TException {
 public:

  static const char* ascii_fingerprint; // = "66E694018C17E5B65A59AE8F55CCA3CD";
  static const uint8_t binary_fingerprint[16]; // = {0x66,0xE6,0x94,0x01,0x8C,0x17,0xE5,0xB6,0x5A,0x59,0xAE,0x8F,0x55,0xCC,0xA3,0xCD};

  SystemException(const SystemException&);
  SystemException& operator=(const SystemException&);
  SystemException() : message() {
  }

  virtual ~SystemException() throw();
  std::string message;

  _SystemException__isset __isset;

  void __set_message(const std::string& val);

  bool operator == (const SystemException & rhs) const
  {
    if (__isset.message != rhs.__isset.message)
      return false;
    else if (__isset.message && !(message == rhs.message))
      return false;
    return true;
  }
  bool operator != (const SystemException &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SystemException & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const SystemException& obj);
};

void swap(SystemException &a, SystemException &b);


class StatusReport {
 public:

  static const char* ascii_fingerprint; // = "8BBB3D0C3B370CB38F2D1340BB79F0AA";
  static const uint8_t binary_fingerprint[16]; // = {0x8B,0xBB,0x3D,0x0C,0x3B,0x37,0x0C,0xB3,0x8F,0x2D,0x13,0x40,0xBB,0x79,0xF0,0xAA};

  StatusReport(const StatusReport&);
  StatusReport& operator=(const StatusReport&);
  StatusReport() : status((Status::type)0) {
  }

  virtual ~StatusReport() throw();
  Status::type status;

  void __set_status(const Status::type val);

  bool operator == (const StatusReport & rhs) const
  {
    if (!(status == rhs.status))
      return false;
    return true;
  }
  bool operator != (const StatusReport &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const StatusReport & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const StatusReport& obj);
};

void swap(StatusReport &a, StatusReport &b);

typedef struct _RFileMetadata__isset {
  _RFileMetadata__isset() : filename(false), created(false), updated(false), version(false), contenthash(false) {}
  bool filename :1;
  bool created :1;
  bool updated :1;
  bool version :1;
  bool contenthash :1;
} _RFileMetadata__isset;

class RFileMetadata {
 public:

  static const char* ascii_fingerprint; // = "29CADA0CEE463BAC0670B6F800004BEC";
  static const uint8_t binary_fingerprint[16]; // = {0x29,0xCA,0xDA,0x0C,0xEE,0x46,0x3B,0xAC,0x06,0x70,0xB6,0xF8,0x00,0x00,0x4B,0xEC};

  RFileMetadata(const RFileMetadata&);
  RFileMetadata& operator=(const RFileMetadata&);
  RFileMetadata() : filename(), created(0), updated(0), version(0), contenthash() {
  }

  virtual ~RFileMetadata() throw();
  std::string filename;
  Timestamp created;
  Timestamp updated;
  int32_t version;
  std::string contenthash;

  _RFileMetadata__isset __isset;

  void __set_filename(const std::string& val);

  void __set_created(const Timestamp val);

  void __set_updated(const Timestamp val);

  void __set_version(const int32_t val);

  void __set_contenthash(const std::string& val);

  bool operator == (const RFileMetadata & rhs) const
  {
    if (__isset.filename != rhs.__isset.filename)
      return false;
    else if (__isset.filename && !(filename == rhs.filename))
      return false;
    if (__isset.created != rhs.__isset.created)
      return false;
    else if (__isset.created && !(created == rhs.created))
      return false;
    if (__isset.updated != rhs.__isset.updated)
      return false;
    else if (__isset.updated && !(updated == rhs.updated))
      return false;
    if (__isset.version != rhs.__isset.version)
      return false;
    else if (__isset.version && !(version == rhs.version))
      return false;
    if (__isset.contenthash != rhs.__isset.contenthash)
      return false;
    else if (__isset.contenthash && !(contenthash == rhs.contenthash))
      return false;
    return true;
  }
  bool operator != (const RFileMetadata &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RFileMetadata & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const RFileMetadata& obj);
};

void swap(RFileMetadata &a, RFileMetadata &b);

typedef struct _Filedes__isset {
  _Filedes__isset() : flag(false), content(false), block(false) {}
  bool flag :1;
  bool content :1;
  bool block :1;
} _Filedes__isset;

class Filedes {
 public:

  static const char* ascii_fingerprint; // = "538B9E45F78E9805971ED8D100FFED5A";
  static const uint8_t binary_fingerprint[16]; // = {0x53,0x8B,0x9E,0x45,0xF7,0x8E,0x98,0x05,0x97,0x1E,0xD8,0xD1,0x00,0xFF,0xED,0x5A};

  Filedes(const Filedes&);
  Filedes& operator=(const Filedes&);
  Filedes() : flag(0), content(), block(0) {
  }

  virtual ~Filedes() throw();
  int32_t flag;
  std::string content;
  int32_t block;

  _Filedes__isset __isset;

  void __set_flag(const int32_t val);

  void __set_content(const std::string& val);

  void __set_block(const int32_t val);

  bool operator == (const Filedes & rhs) const
  {
    if (__isset.flag != rhs.__isset.flag)
      return false;
    else if (__isset.flag && !(flag == rhs.flag))
      return false;
    if (__isset.content != rhs.__isset.content)
      return false;
    else if (__isset.content && !(content == rhs.content))
      return false;
    if (__isset.block != rhs.__isset.block)
      return false;
    else if (__isset.block && !(block == rhs.block))
      return false;
    return true;
  }
  bool operator != (const Filedes &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Filedes & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Filedes& obj);
};

void swap(Filedes &a, Filedes &b);

typedef struct _Filechk__isset {
  _Filechk__isset() : rollchk(false), md5chk(false) {}
  bool rollchk :1;
  bool md5chk :1;
} _Filechk__isset;

class Filechk {
 public:

  static const char* ascii_fingerprint; // = "0354D07C94CB8542872CA1277008860A";
  static const uint8_t binary_fingerprint[16]; // = {0x03,0x54,0xD0,0x7C,0x94,0xCB,0x85,0x42,0x87,0x2C,0xA1,0x27,0x70,0x08,0x86,0x0A};

  Filechk(const Filechk&);
  Filechk& operator=(const Filechk&);
  Filechk() : rollchk(0), md5chk(0) {
  }

  virtual ~Filechk() throw();
  int64_t rollchk;
  int64_t md5chk;

  _Filechk__isset __isset;

  void __set_rollchk(const int64_t val);

  void __set_md5chk(const int64_t val);

  bool operator == (const Filechk & rhs) const
  {
    if (__isset.rollchk != rhs.__isset.rollchk)
      return false;
    else if (__isset.rollchk && !(rollchk == rhs.rollchk))
      return false;
    if (__isset.md5chk != rhs.__isset.md5chk)
      return false;
    else if (__isset.md5chk && !(md5chk == rhs.md5chk))
      return false;
    return true;
  }
  bool operator != (const Filechk &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Filechk & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Filechk& obj);
};

void swap(Filechk &a, Filechk &b);

typedef struct _RFile__isset {
  _RFile__isset() : meta(false), content(false) {}
  bool meta :1;
  bool content :1;
} _RFile__isset;

class RFile {
 public:

  static const char* ascii_fingerprint; // = "40077053B9C9B3A3984700ABD9814964";
  static const uint8_t binary_fingerprint[16]; // = {0x40,0x07,0x70,0x53,0xB9,0xC9,0xB3,0xA3,0x98,0x47,0x00,0xAB,0xD9,0x81,0x49,0x64};

  RFile(const RFile&);
  RFile& operator=(const RFile&);
  RFile() : content() {
  }

  virtual ~RFile() throw();
  RFileMetadata meta;
  std::string content;

  _RFile__isset __isset;

  void __set_meta(const RFileMetadata& val);

  void __set_content(const std::string& val);

  bool operator == (const RFile & rhs) const
  {
    if (__isset.meta != rhs.__isset.meta)
      return false;
    else if (__isset.meta && !(meta == rhs.meta))
      return false;
    if (__isset.content != rhs.__isset.content)
      return false;
    else if (__isset.content && !(content == rhs.content))
      return false;
    return true;
  }
  bool operator != (const RFile &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RFile & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const RFile& obj);
};

void swap(RFile &a, RFile &b);



#endif
