/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "smartSync_constants.h"



const smartSyncConstants g_smartSync_constants;

smartSyncConstants::smartSyncConstants() {
}



